# -*- coding: utf-8 -*-
"""TG_Data_Preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNSEEaX64vmHr5Uxc42Qsi7e6-oU0Jz1

#**Setup**
"""

!pip install datasets evaluate transformers[sentencepiece]
!pip install -U datasets huggingface_hub fsspec

from datasets import load_dataset

"""#**Load Data**"""

ds = load_dataset("azrai99/the-star-news-articles")
ds

"""#**Data Preparation**"""

ds = ds["train"].train_test_split(test_size=0.2)
ds

ds_tst = ds["test"].train_test_split(test_size=0.5)
ds_tst

ds["validation"] = ds_tst["train"]
ds["test"] = ds_tst["test"]
ds

# We only need the Article title and body, so other columns are dropped
rem_cols = ['content_id', 'section', 'category', 'content_tier', 'content_length', 'authors', 'published_date', 'keywords', 'summary', 'url', 'top_image']

for d in ds:
  ds[d] = ds[d].remove_columns(rem_cols)
ds

def show_samples(dataset, num_samples=3, seed=42):
  """Prints random samples from the dataset.
  Args:
      dataset (Dataset): The dataset to show the samples from.
      num_samples (int): The number of samples to show. Defaults to 3.
      seed (int): The starting number to initialize the random number generator.
  """
  sample = dataset["train"].shuffle(seed=seed).select(range(num_samples))
  for example in sample:
    print(f"\n'>> Target Title: {example['title']}'")
    print(f"'>> Article: {example['text']}'")


show_samples(ds)

#Filter only titles of length >2
ds = ds.filter(lambda x: len(x["title"].split()) > 2)
ds

"""#**Save Data**"""

ds.save_to_disk("Data")

# If using colab, Uncomment the following lines to save the data to your google drive.
# from google.colab import drive
# drive.mount('/content/drive')

#!cp -r /content/Data "/content/drive/My Drive/Projects/Title Generator/"